language: node_js
dist: xenial
node_js:
    - 11.0.0

cache: npm

script: npm run check

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_DEPLOY # Set in travis-ci.org dashboard
    local_dir: dist
    on:
        branch: main
